"""Instalação V2 em banco vazio."""
from alembic import op
import sqlalchemy as sa

revision = '20260909_v2'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_budget',
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('next_allowed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('external_lookup_cache',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_external_lookup_cache_expires_at'), 'external_lookup_cache', ['expires_at'], unique=False)
    op.create_table('job_state',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('loja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=True),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('setor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('loja_id', sa.Integer(), nullable=True),
    sa.Column('setor_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("role != 'encarregado_setor' OR setor_id IS NOT NULL", name='ck_usuario_setor'),
    sa.CheckConstraint("role IN ('gerente_geral','gerente_trocas') OR loja_id IS NOT NULL", name='ck_usuario_loja'),
    sa.CheckConstraint("role IN ('gerente_geral','gerente_trocas','gerente','encarregado_setor','auxiliar_gestao')", name='ck_usuario_role'),
    sa.ForeignKeyConstraint(['loja_id'], ['loja.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['setor_id'], ['setor.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_loja_id'), 'usuario', ['loja_id'], unique=False)
    op.create_index(op.f('ix_usuario_setor_id'), 'usuario', ['setor_id'], unique=False)
    op.create_table('email_delivery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_key', sa.String(length=160), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('recipient', sa.String(length=254), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=160), nullable=True),
    sa.CheckConstraint("status IN ('pending','sending','sent','skipped','cancelled','expired','failed','uncertain')", name='ck_delivery_status'),
    sa.CheckConstraint('attempts >= 0', name='ck_delivery_attempts'),
    sa.ForeignKeyConstraint(['user_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('delivery_key')
    )
    op.create_index('ix_delivery_pending', 'email_delivery', ['status', 'next_attempt_at'], unique=False)
    op.create_index('ix_delivery_user_created', 'email_delivery', ['user_id', 'created_at'], unique=False)
    op.create_table('email_preference',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=254), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('frequency', sa.String(length=10), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('minute', sa.Integer(), nullable=False),
    sa.Column('days_min', sa.Integer(), nullable=False),
    sa.Column('days_max', sa.Integer(), nullable=False),
    sa.CheckConstraint("frequency IN ('daily','weekly')", name='ck_email_frequency'),
    sa.CheckConstraint('days_min >= 0 AND days_max >= days_min AND days_max <= 365', name='ck_email_window'),
    sa.CheckConstraint('hour BETWEEN 0 AND 23 AND minute BETWEEN 0 AND 59', name='ck_email_time'),
    sa.CheckConstraint('weekday BETWEEN 0 AND 6', name='ck_email_weekday'),
    sa.ForeignKeyConstraint(['user_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index('ix_email_schedule', 'email_preference', ['enabled', 'verified', 'frequency', 'weekday', 'hour'], unique=False)
    op.create_table('email_token',
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=10), nullable=False),
    sa.Column('address', sa.String(length=254), nullable=False),
    sa.Column('password_stamp', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.CheckConstraint("purpose IN ('reset','verify')", name='ck_token_purpose'),
    sa.ForeignKeyConstraint(['user_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('digest')
    )
    op.create_index(op.f('ix_email_token_expires_at'), 'email_token', ['expires_at'], unique=False)
    op.create_index('ix_token_user_purpose', 'email_token', ['user_id', 'purpose', 'used'], unique=False)
    op.create_table('produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_produto', sa.String(length=200), nullable=False),
    sa.Column('barcode', sa.String(length=14), nullable=False),
    sa.Column('plu', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('source_url', sa.String(length=255), nullable=False),
    sa.Column('marca', sa.String(length=150), nullable=False),
    sa.Column('lote', sa.String(length=80), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('validade', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('data_cadastro', sa.DateTime(timezone=True), nullable=False),
    sa.Column('motivo_rebaixa', sa.String(length=255), nullable=True),
    sa.Column('loja_id', sa.Integer(), nullable=False),
    sa.Column('setor_id', sa.Integer(), nullable=False),
    sa.Column('criado_por_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("source = 'openfoodfacts'", name='ck_produto_source'),
    sa.CheckConstraint("status IN ('Para Rebaixa','Em Rebaixa')", name='ck_produto_status'),
    sa.CheckConstraint('quantidade > 0', name='ck_produto_quantidade'),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuario.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['loja_id'], ['loja.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['setor_id'], ['setor.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produto_barcode'), 'produto', ['barcode'], unique=False)
    op.create_index(op.f('ix_produto_criado_por_id'), 'produto', ['criado_por_id'], unique=False)
    op.create_index('ix_produto_loja_setor_validade', 'produto', ['loja_id', 'setor_id', 'validade'], unique=False)
    op.create_index('ix_produto_status_validade', 'produto', ['status', 'validade'], unique=False)
    op.create_index(op.f('ix_produto_validade'), 'produto', ['validade'], unique=False)
    op.create_table('notificacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_key', sa.String(length=160), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('loja_id', sa.Integer(), nullable=False),
    sa.Column('setor_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("severity IN ('info','warning','critical')", name='ck_notificacao_severity'),
    sa.ForeignKeyConstraint(['loja_id'], ['loja.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['setor_id'], ['setor.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_key')
    )
    op.create_index(op.f('ix_notificacao_produto_id'), 'notificacao', ['produto_id'], unique=False)
    op.create_index('ix_notificacao_scope', 'notificacao', ['loja_id', 'setor_id', 'resolved_at', 'timestamp'], unique=False)
    op.create_table('notificacao_lida',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('notificacao_id', sa.Integer(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['notificacao_id'], ['notificacao.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id', 'notificacao_id')
    )
    # ### end Alembic commands ###
    op.create_index('uq_usuario_username_lower', 'usuario', [sa.text('lower(username)')], unique=True)

def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notificacao_lida')
    op.drop_index('ix_notificacao_scope', table_name='notificacao')
    op.drop_index(op.f('ix_notificacao_produto_id'), table_name='notificacao')
    op.drop_table('notificacao')
    op.drop_index(op.f('ix_produto_validade'), table_name='produto')
    op.drop_index('ix_produto_status_validade', table_name='produto')
    op.drop_index('ix_produto_loja_setor_validade', table_name='produto')
    op.drop_index(op.f('ix_produto_criado_por_id'), table_name='produto')
    op.drop_index(op.f('ix_produto_barcode'), table_name='produto')
    op.drop_table('produto')
    op.drop_index('ix_token_user_purpose', table_name='email_token')
    op.drop_index(op.f('ix_email_token_expires_at'), table_name='email_token')
    op.drop_table('email_token')
    op.drop_index('ix_email_schedule', table_name='email_preference')
    op.drop_table('email_preference')
    op.drop_index('ix_delivery_user_created', table_name='email_delivery')
    op.drop_index('ix_delivery_pending', table_name='email_delivery')
    op.drop_table('email_delivery')
    op.drop_index(op.f('ix_usuario_setor_id'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_loja_id'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_table('setor')
    op.drop_table('loja')
    op.drop_table('job_state')
    op.drop_index(op.f('ix_external_lookup_cache_expires_at'), table_name='external_lookup_cache')
    op.drop_table('external_lookup_cache')
    op.drop_table('api_budget')
    # ### end Alembic commands ###
